language: node_js
node_js:
  - "0.10"
services: mongodb
before_script:
  - npm install -g grunt-cli karma bower
  - cd client
  - npm install
  - bower install
script:
  - grunt
after_script:
  - cd ..
  - server
  - npm install
  - grunt
